//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerhozinaIvanovDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleComments
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public int UserId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Users Users { get; set; }
    }
}
